findent -o3 <..\..\..\src\makeincludes\makeincludes-test.F90> ..\..\..\src\makeincludes\makeincludes-test.F90.new
move /Y  ..\..\..\src\makeincludes\makeincludes-test.F90.new ..\..\..\src\makeincludes\makeincludes-test.F90
findent -o3 <..\..\..\src\makeincludes\makeincludes.F90> ..\..\..\src\makeincludes\makeincludes.F90.new
move /Y  ..\..\..\src\makeincludes\makeincludes.F90.new ..\..\..\src\makeincludes\makeincludes.F90
findent -o3 <..\..\..\src\xbeach\input.F90> ..\..\..\src\xbeach\input.F90.new
move /Y  ..\..\..\src\xbeach\input.F90.new ..\..\..\src\xbeach\input.F90
findent -o3 <..\..\..\src\xbeach\xbeach.F90> ..\..\..\src\xbeach\xbeach.F90.new
move /Y  ..\..\..\src\xbeach\xbeach.F90.new ..\..\..\src\xbeach\xbeach.F90
findent -o3 <..\..\..\src\xbeachlibrary\beachwizard.F90> ..\..\..\src\xbeachlibrary\beachwizard.F90.new
move /Y  ..\..\..\src\xbeachlibrary\beachwizard.F90.new ..\..\..\src\xbeachlibrary\beachwizard.F90
findent -o3 <..\..\..\src\xbeachlibrary\bedroughness.F90> ..\..\..\src\xbeachlibrary\bedroughness.F90.new
move /Y  ..\..\..\src\xbeachlibrary\bedroughness.F90.new ..\..\..\src\xbeachlibrary\bedroughness.F90
findent -o3 <..\..\..\src\xbeachlibrary\boundaryconditions.F90> ..\..\..\src\xbeachlibrary\boundaryconditions.F90.new
move /Y  ..\..\..\src\xbeachlibrary\boundaryconditions.F90.new ..\..\..\src\xbeachlibrary\boundaryconditions.F90
findent -o3 <..\..\..\src\xbeachlibrary\constants.F90> ..\..\..\src\xbeachlibrary\constants.F90.new
move /Y  ..\..\..\src\xbeachlibrary\constants.F90.new ..\..\..\src\xbeachlibrary\constants.F90
findent -o3 <..\..\..\src\xbeachlibrary\debugging.F90> ..\..\..\src\xbeachlibrary\debugging.F90.new
move /Y  ..\..\..\src\xbeachlibrary\debugging.F90.new ..\..\..\src\xbeachlibrary\debugging.F90
findent -o3 <..\..\..\src\xbeachlibrary\demo.F90> ..\..\..\src\xbeachlibrary\demo.F90.new
move /Y  ..\..\..\src\xbeachlibrary\demo.F90.new ..\..\..\src\xbeachlibrary\demo.F90
findent -o3 <..\..\..\src\xbeachlibrary\drifters.F90> ..\..\..\src\xbeachlibrary\drifters.F90.new
move /Y  ..\..\..\src\xbeachlibrary\drifters.F90.new ..\..\..\src\xbeachlibrary\drifters.F90
findent -o3 <..\..\..\src\xbeachlibrary\filefunctions.F90> ..\..\..\src\xbeachlibrary\filefunctions.F90.new
move /Y  ..\..\..\src\xbeachlibrary\filefunctions.F90.new ..\..\..\src\xbeachlibrary\filefunctions.F90
findent -o3 <..\..\..\src\xbeachlibrary\flow_secondorder.F90> ..\..\..\src\xbeachlibrary\flow_secondorder.F90.new
move /Y  ..\..\..\src\xbeachlibrary\flow_secondorder.F90.new ..\..\..\src\xbeachlibrary\flow_secondorder.F90
findent -o3 <..\..\..\src\xbeachlibrary\flow_timestep.F90> ..\..\..\src\xbeachlibrary\flow_timestep.F90.new
move /Y  ..\..\..\src\xbeachlibrary\flow_timestep.F90.new ..\..\..\src\xbeachlibrary\flow_timestep.F90
findent -o3 <..\..\..\src\xbeachlibrary\general_mpi.F90> ..\..\..\src\xbeachlibrary\general_mpi.F90.new
move /Y  ..\..\..\src\xbeachlibrary\general_mpi.F90.new ..\..\..\src\xbeachlibrary\general_mpi.F90
findent -o3 <..\..\..\src\xbeachlibrary\general_mpi_new.F90> ..\..\..\src\xbeachlibrary\general_mpi_new.F90.new
move /Y  ..\..\..\src\xbeachlibrary\general_mpi_new.F90.new ..\..\..\src\xbeachlibrary\general_mpi_new.F90
findent -o3 <..\..\..\src\xbeachlibrary\getkey.F90> ..\..\..\src\xbeachlibrary\getkey.F90.new
move /Y  ..\..\..\src\xbeachlibrary\getkey.F90.new ..\..\..\src\xbeachlibrary\getkey.F90
findent -o3 <..\..\..\src\xbeachlibrary\groundwater.F90> ..\..\..\src\xbeachlibrary\groundwater.F90.new
move /Y  ..\..\..\src\xbeachlibrary\groundwater.F90.new ..\..\..\src\xbeachlibrary\groundwater.F90
findent -o3 <..\..\..\src\xbeachlibrary\indextos.F90> ..\..\..\src\xbeachlibrary\indextos.F90.new
move /Y  ..\..\..\src\xbeachlibrary\indextos.F90.new ..\..\..\src\xbeachlibrary\indextos.F90
findent -o3 <..\..\..\src\xbeachlibrary\initialize.F90> ..\..\..\src\xbeachlibrary\initialize.F90.new
move /Y  ..\..\..\src\xbeachlibrary\initialize.F90.new ..\..\..\src\xbeachlibrary\initialize.F90
findent -o3 <..\..\..\src\xbeachlibrary\interp.F90> ..\..\..\src\xbeachlibrary\interp.F90.new
move /Y  ..\..\..\src\xbeachlibrary\interp.F90.new ..\..\..\src\xbeachlibrary\interp.F90
findent -o3 <..\..\..\src\xbeachlibrary\introspection.F90> ..\..\..\src\xbeachlibrary\introspection.F90.new
move /Y  ..\..\..\src\xbeachlibrary\introspection.F90.new ..\..\..\src\xbeachlibrary\introspection.F90
findent -o3 <..\..\..\src\xbeachlibrary\libxbeach.F90> ..\..\..\src\xbeachlibrary\libxbeach.F90.new
move /Y  ..\..\..\src\xbeachlibrary\libxbeach.F90.new ..\..\..\src\xbeachlibrary\libxbeach.F90
findent -o3 <..\..\..\src\xbeachlibrary\libxbeach_dynamic.F90> ..\..\..\src\xbeachlibrary\libxbeach_dynamic.F90.new
move /Y  ..\..\..\src\xbeachlibrary\libxbeach_dynamic.F90.new ..\..\..\src\xbeachlibrary\libxbeach_dynamic.F90
findent -o3 <..\..\..\src\xbeachlibrary\logging.F90> ..\..\..\src\xbeachlibrary\logging.F90.new
move /Y  ..\..\..\src\xbeachlibrary\logging.F90.new ..\..\..\src\xbeachlibrary\logging.F90
findent -o3 <..\..\..\src\xbeachlibrary\loopcounters.F90> ..\..\..\src\xbeachlibrary\loopcounters.F90.new
move /Y  ..\..\..\src\xbeachlibrary\loopcounters.F90.new ..\..\..\src\xbeachlibrary\loopcounters.F90
findent -o3 <..\..\..\src\xbeachlibrary\math_tools.F90> ..\..\..\src\xbeachlibrary\math_tools.F90.new
move /Y  ..\..\..\src\xbeachlibrary\math_tools.F90.new ..\..\..\src\xbeachlibrary\math_tools.F90
findent -o3 <..\..\..\src\xbeachlibrary\mnemonic.F90> ..\..\..\src\xbeachlibrary\mnemonic.F90.new
move /Y  ..\..\..\src\xbeachlibrary\mnemonic.F90.new ..\..\..\src\xbeachlibrary\mnemonic.F90
findent -o3 <..\..\..\src\xbeachlibrary\mnemoniciso.F90> ..\..\..\src\xbeachlibrary\mnemoniciso.F90.new
move /Y  ..\..\..\src\xbeachlibrary\mnemoniciso.F90.new ..\..\..\src\xbeachlibrary\mnemoniciso.F90
findent -o3 <..\..\..\src\xbeachlibrary\morphevolution.F90> ..\..\..\src\xbeachlibrary\morphevolution.F90.new
move /Y  ..\..\..\src\xbeachlibrary\morphevolution.F90.new ..\..\..\src\xbeachlibrary\morphevolution.F90
findent -o3 <..\..\..\src\xbeachlibrary\ncoutput.F90> ..\..\..\src\xbeachlibrary\ncoutput.F90.new
move /Y  ..\..\..\src\xbeachlibrary\ncoutput.F90.new ..\..\..\src\xbeachlibrary\ncoutput.F90
findent -o3 <..\..\..\src\xbeachlibrary\nonh.F90> ..\..\..\src\xbeachlibrary\nonh.F90.new
move /Y  ..\..\..\src\xbeachlibrary\nonh.F90.new ..\..\..\src\xbeachlibrary\nonh.F90
findent -o3 <..\..\..\src\xbeachlibrary\output.F90> ..\..\..\src\xbeachlibrary\output.F90.new
move /Y  ..\..\..\src\xbeachlibrary\output.F90.new ..\..\..\src\xbeachlibrary\output.F90
findent -o3 <..\..\..\src\xbeachlibrary\params.F90> ..\..\..\src\xbeachlibrary\params.F90.new
move /Y  ..\..\..\src\xbeachlibrary\params.F90.new ..\..\..\src\xbeachlibrary\params.F90
findent -o3 <..\..\..\src\xbeachlibrary\paramsconst.F90> ..\..\..\src\xbeachlibrary\paramsconst.F90.new
move /Y  ..\..\..\src\xbeachlibrary\paramsconst.F90.new ..\..\..\src\xbeachlibrary\paramsconst.F90
findent -o3 <..\..\..\src\xbeachlibrary\postprocess.F90> ..\..\..\src\xbeachlibrary\postprocess.F90.new
move /Y  ..\..\..\src\xbeachlibrary\postprocess.F90.new ..\..\..\src\xbeachlibrary\postprocess.F90
findent -o3 <..\..\..\src\xbeachlibrary\readkey.F90> ..\..\..\src\xbeachlibrary\readkey.F90.new
move /Y  ..\..\..\src\xbeachlibrary\readkey.F90.new ..\..\..\src\xbeachlibrary\readkey.F90
findent -o3 <..\..\..\src\xbeachlibrary\readtide.F90> ..\..\..\src\xbeachlibrary\readtide.F90.new
move /Y  ..\..\..\src\xbeachlibrary\readtide.F90.new ..\..\..\src\xbeachlibrary\readtide.F90
findent -o3 <..\..\..\src\xbeachlibrary\readwind.F90> ..\..\..\src\xbeachlibrary\readwind.F90.new
move /Y  ..\..\..\src\xbeachlibrary\readwind.F90.new ..\..\..\src\xbeachlibrary\readwind.F90
findent -o3 <..\..\..\src\xbeachlibrary\roelvink.F90> ..\..\..\src\xbeachlibrary\roelvink.F90.new
move /Y  ..\..\..\src\xbeachlibrary\roelvink.F90.new ..\..\..\src\xbeachlibrary\roelvink.F90
findent -o3 <..\..\..\src\xbeachlibrary\ship.F90> ..\..\..\src\xbeachlibrary\ship.F90.new
move /Y  ..\..\..\src\xbeachlibrary\ship.F90.new ..\..\..\src\xbeachlibrary\ship.F90
findent -o3 <..\..\..\src\xbeachlibrary\sleeper.F90> ..\..\..\src\xbeachlibrary\sleeper.F90.new
move /Y  ..\..\..\src\xbeachlibrary\sleeper.F90.new ..\..\..\src\xbeachlibrary\sleeper.F90
findent -o3 <..\..\..\src\xbeachlibrary\solver.F90> ..\..\..\src\xbeachlibrary\solver.F90.new
move /Y  ..\..\..\src\xbeachlibrary\solver.F90.new ..\..\..\src\xbeachlibrary\solver.F90
findent -o3 <..\..\..\src\xbeachlibrary\spaceparams.F90> ..\..\..\src\xbeachlibrary\spaceparams.F90.new
move /Y  ..\..\..\src\xbeachlibrary\spaceparams.F90.new ..\..\..\src\xbeachlibrary\spaceparams.F90
findent -o3 <..\..\..\src\xbeachlibrary\spaceparamsdef.F90> ..\..\..\src\xbeachlibrary\spaceparamsdef.F90.new
move /Y  ..\..\..\src\xbeachlibrary\spaceparamsdef.F90.new ..\..\..\src\xbeachlibrary\spaceparamsdef.F90
findent -o3 <..\..\..\src\xbeachlibrary\timestep.F90> ..\..\..\src\xbeachlibrary\timestep.F90.new
move /Y  ..\..\..\src\xbeachlibrary\timestep.F90.new ..\..\..\src\xbeachlibrary\timestep.F90
findent -o3 <..\..\..\src\xbeachlibrary\typesandkinds.F90> ..\..\..\src\xbeachlibrary\typesandkinds.F90.new
move /Y  ..\..\..\src\xbeachlibrary\typesandkinds.F90.new ..\..\..\src\xbeachlibrary\typesandkinds.F90
findent -o3 <..\..\..\src\xbeachlibrary\varianceupdate.F90> ..\..\..\src\xbeachlibrary\varianceupdate.F90.new
move /Y  ..\..\..\src\xbeachlibrary\varianceupdate.F90.new ..\..\..\src\xbeachlibrary\varianceupdate.F90
findent -o3 <..\..\..\src\xbeachlibrary\varoutput.F90> ..\..\..\src\xbeachlibrary\varoutput.F90.new
move /Y  ..\..\..\src\xbeachlibrary\varoutput.F90.new ..\..\..\src\xbeachlibrary\varoutput.F90
findent -o3 <..\..\..\src\xbeachlibrary\vegetation.F90> ..\..\..\src\xbeachlibrary\vegetation.F90.new
move /Y  ..\..\..\src\xbeachlibrary\vegetation.F90.new ..\..\..\src\xbeachlibrary\vegetation.F90
findent -o3 <..\..\..\src\xbeachlibrary\wave_bc_nextgen.f90> ..\..\..\src\xbeachlibrary\wave_bc_nextgen.f90.new
move /Y  ..\..\..\src\xbeachlibrary\wave_bc_nextgen.f90.new ..\..\..\src\xbeachlibrary\wave_bc_nextgen.f90
findent -o3 <..\..\..\src\xbeachlibrary\wave_boundary_datastore.f90> ..\..\..\src\xbeachlibrary\wave_boundary_datastore.f90.new
move /Y  ..\..\..\src\xbeachlibrary\wave_boundary_datastore.f90.new ..\..\..\src\xbeachlibrary\wave_boundary_datastore.f90
findent -o3 <..\..\..\src\xbeachlibrary\wave_boundary_init.f90> ..\..\..\src\xbeachlibrary\wave_boundary_init.f90.new
move /Y  ..\..\..\src\xbeachlibrary\wave_boundary_init.f90.new ..\..\..\src\xbeachlibrary\wave_boundary_init.f90
findent -o3 <..\..\..\src\xbeachlibrary\wave_boundary_main.f90> ..\..\..\src\xbeachlibrary\wave_boundary_main.f90.new
move /Y  ..\..\..\src\xbeachlibrary\wave_boundary_main.f90.new ..\..\..\src\xbeachlibrary\wave_boundary_main.f90
findent -o3 <..\..\..\src\xbeachlibrary\wave_boundary_update.f90> ..\..\..\src\xbeachlibrary\wave_boundary_update.f90.new
move /Y  ..\..\..\src\xbeachlibrary\wave_boundary_update.f90.new ..\..\..\src\xbeachlibrary\wave_boundary_update.f90
findent -o3 <..\..\..\src\xbeachlibrary\wave_directions.F90> ..\..\..\src\xbeachlibrary\wave_directions.F90.new
move /Y  ..\..\..\src\xbeachlibrary\wave_directions.F90.new ..\..\..\src\xbeachlibrary\wave_directions.F90
findent -o3 <..\..\..\src\xbeachlibrary\wave_functions.F90> ..\..\..\src\xbeachlibrary\wave_functions.F90.new
move /Y  ..\..\..\src\xbeachlibrary\wave_functions.F90.new ..\..\..\src\xbeachlibrary\wave_functions.F90
findent -o3 <..\..\..\src\xbeachlibrary\wave_instationary.F90> ..\..\..\src\xbeachlibrary\wave_instationary.F90.new
move /Y  ..\..\..\src\xbeachlibrary\wave_instationary.F90.new ..\..\..\src\xbeachlibrary\wave_instationary.F90
findent -o3 <..\..\..\src\xbeachlibrary\wave_stationary.F90> ..\..\..\src\xbeachlibrary\wave_stationary.F90.new
move /Y  ..\..\..\src\xbeachlibrary\wave_stationary.F90.new ..\..\..\src\xbeachlibrary\wave_stationary.F90
findent -o3 <..\..\..\src\xbeachlibrary\wave_timestep.F90> ..\..\..\src\xbeachlibrary\wave_timestep.F90.new
move /Y  ..\..\..\src\xbeachlibrary\wave_timestep.F90.new ..\..\..\src\xbeachlibrary\wave_timestep.F90
findent -o3 <..\..\..\src\xbeachlibrary\waveparams.F90> ..\..\..\src\xbeachlibrary\waveparams.F90.new
move /Y  ..\..\..\src\xbeachlibrary\waveparams.F90.new ..\..\..\src\xbeachlibrary\waveparams.F90
findent -o3 <..\..\..\src\xbeachlibrary\waveparamsnew.F90> ..\..\..\src\xbeachlibrary\waveparamsnew.F90.new
move /Y  ..\..\..\src\xbeachlibrary\waveparamsnew.F90.new ..\..\..\src\xbeachlibrary\waveparamsnew.F90
findent -o3 <..\..\..\src\xbeachlibrary\xmpi.F90> ..\..\..\src\xbeachlibrary\xmpi.F90.new
move /Y  ..\..\..\src\xbeachlibrary\xmpi.F90.new ..\..\..\src\xbeachlibrary\xmpi.F90
findent -o3 <..\..\..\src\xbeachlibrary\xmpinew.F90> ..\..\..\src\xbeachlibrary\xmpinew.F90.new
move /Y  ..\..\..\src\xbeachlibrary\xmpinew.F90.new ..\..\..\src\xbeachlibrary\xmpinew.F90
