!  DO NOT EDIT THIS FILE
!  But edit variables.f90 and scripts/generate.py
!  Compiling and running is taken care of by the Makefile

<%
maxnamelen = max(len(variable["name"]) for variable in variables)
%>

        select case(line)
%for i, var in enumerate(variables):
          case(mnem_${var['name'].ljust(maxnamelen)})
             chartoindex = ${i+1}
%endfor
        end select
!directions for vi vim: filetype=fortran : syntax=fortran
