!  DO NOT EDIT THIS FILE
!  But edit variable.f90 and scripts/generate.py
!  Compiling and running is taken care of by the Makefile

<%
numvars = len(variables)
maxnamelen = max(len(variable["name"]) for variable in variables)
def rank(variable):
    return len(variable["shape"])
maxrank = max(rank(variable) for variable in variables)
%>
        integer, parameter :: numvars    =  ${numvars}
        integer, parameter :: maxnamelen =   ${maxnamelen}
        integer, parameter :: maxrank =    ${maxrank}
%for var in variables:
        character(len=slen),parameter ::  mnem_${var['name'].ljust(maxnamelen)} = '${var['name'].ljust(maxnamelen)}'
%endfor
        character(len=slen),dimension(numvars),parameter :: mnemonics= (/ &
%for i, var in enumerate(variables):
         mnem_${var['name'].ljust(maxnamelen)}${"," if i != len(variables)-1 else ''} & ! ${i+1}
%endfor
        /)
!directions for vi vim: filetype=fortran : syntax=fortran
