!  DO NOT EDIT THIS FILE
!  But edit spaceparams.tmpl and/or makeincludes.F90
!  compile makeincludes.F90 and run the compilate
!  Compiling and running is taken care of by the Makefile
%for variable in variables:
    ${variable['name']} => s%${variable['name']}
%endfor

!directions for vi vim: filetype=fortran : syntax=fortran
