!  DO NOT EDIT THIS FILE
!  But edit variable.f90 and scripts/generate.py
!  Compiling and running is taken care of by the Makefile

%for var in variables:
%if len(var["shape"]) == 0:
  allocate(s%${var['name']})
%endif
%endfor

!directions for vi vim: filetype=fortran : syntax=fortran
